import {
    a11yDark,
    a11yLight,
    agate,
    anOldHope,
    androidstudio,
    arduinoLight,
    arta,
    ascetic,
    atelierCaveDark,
    atelierCaveLight,
    atelierDuneDark,
    atelierDuneLight,
    atelierEstuaryDark,
    atelierEstuaryLight,
    atelierForestDark,
    atelierForestLight,
    atelierHeathDark,
    atelierHeathLight,
    atelierLakesideDark,
    atelierLakesideLight,
    atelierPlateauDark,
    atelierPlateauLight,
    atelierSavannaDark,
    atelierSavannaLight,
    atelierSeasideDark,
    atelierSeasideLight,
    atelierSulphurpoolDark,
    atelierSulphurpoolLight,
    atomOneDark,
    atomOneDarkReasonable,
    atomOneLight,
    brownPaper,
    codepenEmbed,
    colorBrewer,
    darcula,
    dark,
    defaultStyle,
    docco,
    dracula,
    far,
    foundation,
    github,
    githubGist,
    gml,
    googlecode,
    gradientDark,
    grayscale,
    gruvboxDark,
    gruvboxLight,
    hopscotch,
    hybrid,
    idea,
    irBlack,
    isblEditorDark,
    isblEditorLight,
    kimbieDark,
    kimbieLight,
    lightfair,
    lioshi,
    magula,
    monoBlue,
    monokai,
    monokaiSublime,
    nightOwl,
    nnfx,
    nnfxDark,
    nord,
    obsidian,
    ocean,
    paraisoDark,
    paraisoLight,
    pojoaque,
    purebasic,
    qtcreatorDark,
    qtcreatorLight,
    railscasts,
    rainbow,
    routeros,
    schoolBook,
    shadesOfPurple,
    solarizedDark,
    solarizedLight,
    srcery,
    stackoverflowDark,
    stackoverflowLight,
    sunburst,
    tomorrow,
    tomorrowNight,
    tomorrowNightBlue,
    tomorrowNightBright,
    tomorrowNightEighties,
    vs,
    vs2015,
    xcode,
    xt256,
    zenburn
} from 'react-syntax-highlighter/dist/esm/styles/hljs';

export const _THEME = [
    a11yDark,
    a11yLight,
    agate,
    anOldHope,
    androidstudio,
    arduinoLight,
    arta,
    ascetic,
    atelierCaveDark,
    atelierCaveLight,
    atelierDuneDark,
    atelierDuneLight,
    atelierEstuaryDark,
    atelierEstuaryLight,
    atelierForestDark,
    atelierForestLight,
    atelierHeathDark,
    atelierHeathLight,
    atelierLakesideDark,
    atelierLakesideLight,
    atelierPlateauDark,
    atelierPlateauLight,
    atelierSavannaDark,
    atelierSavannaLight,
    atelierSeasideDark,
    atelierSeasideLight,
    atelierSulphurpoolDark,
    atelierSulphurpoolLight,
    atomOneDarkReasonable,
    atomOneDark,
    atomOneLight,
    brownPaper,
    codepenEmbed,
    colorBrewer,
    darcula,
    dark,
    defaultStyle,
    docco,
    dracula,
    far,
    foundation,
    githubGist,
    github,
    gml,
    googlecode,
    gradientDark,
    grayscale,
    gruvboxDark,
    gruvboxLight,
    hopscotch,
    hybrid,
    idea,
    irBlack,
    isblEditorDark,
    isblEditorLight,
    kimbieDark,
    kimbieLight,
    lightfair,
    lioshi,
    magula,
    monoBlue,
    monokaiSublime,
    monokai,
    nightOwl,
    nnfxDark,
    nnfx,
    nord,
    obsidian,
    ocean,
    paraisoDark,
    paraisoLight,
    pojoaque,
    purebasic,
    qtcreatorDark,
    qtcreatorLight,
    railscasts,
    rainbow,
    routeros,
    schoolBook,
    shadesOfPurple,
    solarizedDark,
    solarizedLight,
    srcery,
    stackoverflowDark,
    stackoverflowLight,
    sunburst,
    tomorrowNightBlue,
    tomorrowNightBright,
    tomorrowNightEighties,
    tomorrowNight,
    tomorrow,
    vs,
    vs2015,
    xcode,
    xt256,
    zenburn
];

export const THEME = [
    'a11yDark ',
    'a11yLight ',
    'agate ',
    'anOldHope ',
    'androidstudio ',
    'arduinoLight ',
    'arta ',
    'ascetic ',
    'atelierCaveDark ',
    'atelierCaveLight ',
    'atelierDuneDark ',
    'atelierDuneLight ',
    'atelierEstuaryDark ',
    'atelierEstuaryLight ',
    'atelierForestDark ',
    'atelierForestLight ',
    'atelierHeathDark ',
    'atelierHeathLight ',
    'atelierLakesideDark ',
    'atelierLakesideLight ',
    'atelierPlateauDark ',
    'atelierPlateauLight ',
    'atelierSavannaDark ',
    'atelierSavannaLight ',
    'atelierSeasideDark ',
    'atelierSeasideLight ',
    'atelierSulphurpoolDark ',
    'atelierSulphurpoolLight ',
    'atomOneDarkReasonable ',
    'atomOneDark ',
    'atomOneLight ',
    'brownPaper ',
    'codepenEmbed ',
    'colorBrewer ',
    'darcula ',
    'dark ',
    'defaultStyle ',
    'docco ',
    'dracula ',
    'far ',
    'foundation ',
    'githubGist ',
    'github ',
    'gml ',
    'googlecode ',
    'gradientDark ',
    'grayscale ',
    'gruvboxDark ',
    'gruvboxLight ',
    'hopscotch ',
    'hybrid ',
    'idea ',
    'irBlack ',
    'isblEditorDark ',
    'isblEditorLight ',
    'kimbieDark ',
    'kimbieLight ',
    'lightfair ',
    'lioshi ',
    'magula ',
    'monoBlue ',
    'monokaiSublime ',
    'monokai ',
    'nightOwl ',
    'nnfxDark ',
    'nnfx ',
    'nord ',
    'obsidian ',
    'ocean ',
    'paraisoDark ',
    'paraisoLight ',
    'pojoaque ',
    'purebasic ',
    'qtcreatorDark ',
    'qtcreatorLight ',
    'railscasts ',
    'rainbow ',
    'routeros ',
    'schoolBook ',
    'shadesOfPurple ',
    'solarizedDark ',
    'solarizedLight ',
    'srcery ',
    'stackoverflowDark ',
    'stackoverflowLight ',
    'sunburst ',
    'tomorrowNightBlue ',
    'tomorrowNightBright ',
    'tomorrowNightEighties ',
    'tomorrowNight ',
    'tomorrow ',
    'vs ',
    'vs2015 ',
    'xcode ',
    'xt256 ',
    'zenburn'
];
